on: [push, pull_request]
name: Test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: test wasmd
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.2
      - name: Checkout code
        uses: actions/checkout@v3
      - name: downlaod wasmvm
        run: wget https://github.com/CosmWasm/wasmvm/releases/download/${WASMVM_VERSION}/libwasmvm_muslc.x86_64.a -O /lib/libwasmvm_muslc.x86_64.a

      - name: Test
        run: make test
